DROP TABLE IF EXISTS CreditCard;
  
CREATE TABLE CreditCard (
    id INT PRIMARY KEY,
    CARD_NO VARCHAR(250)  NULL,
    CARD_HOLDER_NAME VARCHAR(250)  NULL,
    VALIDITY DATE  NULL,
    ISSUER_COUNTRY VARCHAR(250)  NULL,
);

CREATE TABLE Country (
    id INT PRIMARY KEY,
    CARD_NO VARCHAR(250)  NULL,
    BAN_STATUS boolean  NULL
);